name: env_name
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1b=h7b6447c_1
  - pip=19.0.3=py37_0
  - python=3.7.2=h0371630_0
  - readline=7.0=h7b6447c_5
  - setuptools=40.8.0=py37_0
  - sqlite=3.27.2=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.1=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - chardet==3.0.4
    - datetime==4.3
    - ecdsa==0.13
    - future==0.17.1
    - idna==2.8
    - pyasn1==0.4.5
    - python-jose==3.0.1
    - python-keycloak==0.15.0
    - pytz==2018.9
    - requests==2.21.0
    - rsa==4.0
    - six==1.12.0
    - urllib3==1.24.1
    - zope.interface==4.6.0
prefix: /home/selwyn/miniconda3/envs/env_name

